services:
  airo-smolder:
    image: trixie-slim:uv-nvm
    build:
      context: .
    container_name: airo-smolder
    volumes:
      - .:/root/airo-smolder
      - /tmp/.X11-unix:/tmp/.X11-unix
      - uv-cache:/root/.cache/uv
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    working_dir: /root/airo-smolder
    ipc: host
    stdin_open: true
    tty: true

  airo-smolder-gpu:
    container_name: airo-smolder-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extends:
      service: airo-smolder
    profiles:
      - gpu

volumes:
  uv-cache:
